"""add password reset codes

Revision ID: 0098f3821b41
Revises: 90566d0d360f
Create Date: 2026-09-11 16:51:05.132633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0098f3821b41'
down_revision = '90566d0d360f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_codes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_codes_expires_at'))

    op.drop_table('password_reset_codes')
    # ### end Alembic commands ###
