"""Add relationships

Revision ID: 064d1d620b33
Revises: 3a42c6991fb7
Create Date: 2026-08-22 20:30:03.826334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064d1d620b33'
down_revision = '3a42c6991fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_a_id', sa.UUID(), nullable=False),
    sa.Column('person_b_id', sa.UUID(), nullable=False),
    sa.Column('relation_a_to_b', sa.String(length=30), nullable=False),
    sa.Column('relation_b_to_a', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_a_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_b_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_person_a_id'), ['person_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_person_b_id'), ['person_b_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_person_b_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_person_a_id'))

    op.drop_table('relationships')
    # ### end Alembic commands ###
