"""Support non user relatives

Revision ID: 07e6ead923bc
Revises: 064d1d620b33
Create Date: 2026-08-24 20:54:03.915048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e6ead923bc'
down_revision = '064d1d620b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_people_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=20), server_default='verified', nullable=False))
        batch_op.create_index(batch_op.f('ix_relationships_verification_status'), ['verification_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_verification_status'))
        batch_op.drop_column('verification_status')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_people_created_by_user_id'))
        batch_op.drop_column('created_by_user_id')

    # ### end Alembic commands ###
