"""revise historical tree to family groups

Revision ID: 23d83006d25a
Revises: c569be8fd5c2
Create Date: 2026-09-17 23:28:07.517381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d83006d25a'
down_revision = 'c569be8fd5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_people_group_id'))
        batch_op.drop_constraint(batch_op.f('historical_people_group_id_fkey'), type_='foreignkey')
        batch_op.drop_column('group_id')

    with op.batch_alter_table('historical_tree_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head_person_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_historical_tree_groups_head_person_id'), ['head_person_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_historical_tree_groups_sort_order'), ['sort_order'], unique=False)
        batch_op.create_foreign_key(None, 'historical_people', ['head_person_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_tree_groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_historical_tree_groups_sort_order'))
        batch_op.drop_index(batch_op.f('ix_historical_tree_groups_head_person_id'))
        batch_op.drop_column('sort_order')
        batch_op.drop_column('head_person_id')

    with op.batch_alter_table('historical_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('historical_people_group_id_fkey'), 'historical_tree_groups', ['group_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_historical_people_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###
