"""Add relationship requests

Revision ID: 3a42c6991fb7
Revises: 5a5538358ddd
Create Date: 2026-08-22 20:12:59.819860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a42c6991fb7'
down_revision = '5a5538358ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_person_id', sa.UUID(), nullable=False),
    sa.Column('receiver_person_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationship_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationship_requests_receiver_person_id'), ['receiver_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_requests_sender_person_id'), ['sender_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationship_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationship_requests_status'))
        batch_op.drop_index(batch_op.f('ix_relationship_requests_sender_person_id'))
        batch_op.drop_index(batch_op.f('ix_relationship_requests_receiver_person_id'))

    op.drop_table('relationship_requests')
    # ### end Alembic commands ###
