"""add community posts

Revision ID: 6597ceb7afac
Revises: c91a7f4d0e21
Create Date: 2026-09-01 23:12:40.255300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6597ceb7afac'
down_revision = 'c91a7f4d0e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('post_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_posts_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_event_at'), ['event_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_post_type'), ['post_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_posts_post_type'))
        batch_op.drop_index(batch_op.f('ix_community_posts_event_at'))
        batch_op.drop_index(batch_op.f('ix_community_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_community_posts_author_user_id'))

    op.drop_table('community_posts')
    # ### end Alembic commands ###
