"""Hash and expire claim codes

Revision ID: 809bf6b7e406
Revises: 23903ba864f8
Create Date: 2026-08-28 22:32:41.861752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809bf6b7e406'
down_revision = '23903ba864f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claim_code_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('claim_code_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_index(batch_op.f('ix_people_claim_code'))
        batch_op.create_index(batch_op.f('ix_people_claim_code_expires_at'), ['claim_code_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_claim_code_hash'), ['claim_code_hash'], unique=True)
        batch_op.drop_column('claim_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claim_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_people_claim_code_hash'))
        batch_op.drop_index(batch_op.f('ix_people_claim_code_expires_at'))
        batch_op.create_index(batch_op.f('ix_people_claim_code'), ['claim_code'], unique=True)
        batch_op.drop_column('claim_code_expires_at')
        batch_op.drop_column('claim_code_hash')

    # ### end Alembic commands ###
