"""add umkm applications

Revision ID: 90566d0d360f
Revises: bea0584a84aa
Create Date: 2026-09-10 23:52:22.782138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90566d0d360f'
down_revision = 'bea0584a84aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('umkm_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_category', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nik', sa.String(length=32), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('umkm_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_umkm_applications_business_name'), ['business_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_umkm_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_umkm_applications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('umkm_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_umkm_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_umkm_applications_status'))
        batch_op.drop_index(batch_op.f('ix_umkm_applications_business_name'))

    op.drop_table('umkm_applications')
    # ### end Alembic commands ###
