"""add culture image urls

Revision ID: 91edf9424572
Revises: f46446f88218
Create Date: 2026-09-15 17:46:18.917484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91edf9424572'
down_revision = 'f46446f88218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('culture_contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('culture_contents', schema=None) as batch_op:
        batch_op.drop_column('image_urls')

    # ### end Alembic commands ###
