"""add community reports and user blocks

Revision ID: 9e0817b1943f
Revises: 23d83006d25a
Create Date: 2026-09-22 20:32:40.170731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0817b1943f'
down_revision = '23d83006d25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blocker_user_id', sa.UUID(), nullable=False),
    sa.Column('blocked_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_user_id', 'blocked_user_id', name='uq_user_blocks_blocker_blocked')
    )
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_blocks_blocked_user_id'), ['blocked_user_id'], unique=False)
        batch_op.create_index('ix_user_blocks_blocker_created_at', ['blocker_user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_blocks_blocker_user_id'), ['blocker_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_blocks_created_at'), ['created_at'], unique=False)

    op.create_table('community_post_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('reporter_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'reporter_user_id', name='uq_community_post_reports_post_reporter')
    )
    with op.batch_alter_table('community_post_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_post_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_reports_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_reports_reporter_user_id'), ['reporter_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_reports_status'), ['status'], unique=False)
        batch_op.create_index('ix_community_post_reports_status_created_at', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_post_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_community_post_reports_status_created_at')
        batch_op.drop_index(batch_op.f('ix_community_post_reports_status'))
        batch_op.drop_index(batch_op.f('ix_community_post_reports_reporter_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_post_reports_post_id'))
        batch_op.drop_index(batch_op.f('ix_community_post_reports_created_at'))

    op.drop_table('community_post_reports')
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_blocks_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_blocks_blocker_user_id'))
        batch_op.drop_index('ix_user_blocks_blocker_created_at')
        batch_op.drop_index(batch_op.f('ix_user_blocks_blocked_user_id'))

    op.drop_table('user_blocks')
    # ### end Alembic commands ###
