"""remove NIK fields

Revision ID: aa7cb88d2b19
Revises: 91edf9424572
Create Date: 2026-09-17 21:45:33.930944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7cb88d2b19'
down_revision = '91edf9424572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('people_nik_key'), type_='unique')
        batch_op.drop_column('nik')

    with op.batch_alter_table('umkm_applications', schema=None) as batch_op:
        batch_op.drop_column('nik')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('umkm_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nik', sa.VARCHAR(length=32), autoincrement=False, nullable=True))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nik', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('people_nik_key'), ['nik'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
