"""add historical genealogy

Revision ID: bea0584a84aa
Revises: d93642479d94
Create Date: 2026-09-10 23:22:02.459241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea0584a84aa'
down_revision = 'd93642479d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('birth_year', sa.String(length=50), nullable=True),
    sa.Column('death_year', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_people_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_people_name'), ['name'], unique=False)

    op.create_table('historical_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), server_default='parent', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('parent_id <> child_id', name='ck_historical_relationship_different_people'),
    sa.ForeignKeyConstraint(['child_id'], ['historical_people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['historical_people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'child_id', 'relationship_type', name='uq_historical_relationship_parent_child_type')
    )
    with op.batch_alter_table('historical_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_relationships_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_relationships_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_relationships_parent_id'))
        batch_op.drop_index(batch_op.f('ix_historical_relationships_child_id'))

    op.drop_table('historical_relationships')
    with op.batch_alter_table('historical_people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_people_name'))
        batch_op.drop_index(batch_op.f('ix_historical_people_is_published'))

    op.drop_table('historical_people')
    # ### end Alembic commands ###
