"""add scaling indexes

Revision ID: c569be8fd5c2
Revises: fb20ee5846ce
Create Date: 2026-09-17 22:47:37.570495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c569be8fd5c2'
down_revision = 'fb20ee5846ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.create_index('ix_community_posts_type_created_at', ['post_type', 'created_at'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_active_category_created_at', ['is_active', 'category', 'created_at'], unique=False)
        batch_op.create_index('ix_products_active_created_at', ['is_active', 'created_at'], unique=False)
        batch_op.create_index('ix_products_seller_created_at', ['seller_user_id', 'created_at'], unique=False)

    with op.batch_alter_table('umkm_applications', schema=None) as batch_op:
        batch_op.create_index('ix_umkm_applications_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_umkm_applications_user_created_at', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('umkm_applications', schema=None) as batch_op:
        batch_op.drop_index('ix_umkm_applications_user_created_at')
        batch_op.drop_index('ix_umkm_applications_status_created_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_seller_created_at')
        batch_op.drop_index('ix_products_active_created_at')
        batch_op.drop_index('ix_products_active_category_created_at')

    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_index('ix_community_posts_type_created_at')

    # ### end Alembic commands ###
