"""add culture contents

Revision ID: d93642479d94
Revises: 6f7c6f465a31
Create Date: 2026-09-10 14:54:52.742790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93642479d94'
down_revision = '6f7c6f465a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('culture_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('culture_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_culture_contents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_culture_contents_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_culture_contents_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('culture_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_culture_contents_title'))
        batch_op.drop_index(batch_op.f('ix_culture_contents_is_published'))
        batch_op.drop_index(batch_op.f('ix_culture_contents_category'))

    op.drop_table('culture_contents')
    # ### end Alembic commands ###
