"""add historical tree groups

Revision ID: fb20ee5846ce
Revises: aa7cb88d2b19
Create Date: 2026-09-17 21:54:36.612331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb20ee5846ce'
down_revision = 'aa7cb88d2b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_tree_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_tree_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_tree_groups_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_tree_groups_name'), ['name'], unique=True)

    with op.batch_alter_table('historical_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_historical_people_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key(None, 'historical_tree_groups', ['group_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_historical_people_group_id'))
        batch_op.drop_column('group_id')

    with op.batch_alter_table('historical_tree_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_tree_groups_name'))
        batch_op.drop_index(batch_op.f('ix_historical_tree_groups_is_published'))

    op.drop_table('historical_tree_groups')
    # ### end Alembic commands ###
